name: HidenCloud Auto Renew

on:
  schedule:
    - cron: '0 18 * * *'  # 每天 UTC 1:00 (北京时间 9:00) 运行
  workflow_dispatch:

jobs:
  auto-renew:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install playwright
        playwright install chromium

    - name: Run HidenCloud SignIn
      env:
        HIDEN_EMAIL: ${{ secrets.HIDEN_EMAIL }}
        HIDEN_PASSWORD: ${{ secrets.HIDEN_PASSWORD }}
        HIDEN_COOKIE: ${{ secrets.HIDEN_COOKIE }}
        HIDEN_SERVICE_URL: ${{ secrets.HIDEN_SERVICE_URL }}
      run: python main.py

    - name: Commit README
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        if git diff --cached --quiet; then
          echo "README 无变化"
        else
          git commit -m "📝 更新签到状态: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin HEAD:main
        fi
